# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venaqui < Formula
  desc "CLI tool with TUI for downloading files via Real-Debrid and aria2"
  homepage "https://github.com/mhrsntrk/venaqui"
  version "0.1.6"
  license "MIT"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.6/venaqui_0.1.6_darwin_amd64.tar.gz"
      sha256 "0a6e343052f143851daa8483969ba980022dacbc50f18524ae2faa6775b1819b"

      def install
        bin.install "venaqui"
      end
    end
    on_arm do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.6/venaqui_0.1.6_darwin_arm64.tar.gz"
      sha256 "245dad753ddd94aa3ad449aab56a618e77a0ebc64870d2c56252e6dda7ba5f3f"

      def install
        bin.install "venaqui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.6/venaqui_0.1.6_linux_amd64.tar.gz"
        sha256 "8372513ed66b68228ec031d0c93cec39a22f5d20706e2e98a8a69017c2e68373"

        def install
          bin.install "venaqui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v0.1.6/venaqui_0.1.6_linux_arm64.tar.gz"
        sha256 "e96697bf19e51a86e134f5b1503a954c021063f8fb1ad1705241600adea71127"

        def install
          bin.install "venaqui"
        end
      end
    end
  end

  test do
    system "#{bin}/venaqui", "version"
  end
end
