# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venaqui < Formula
  desc "CLI tool with TUI for downloading files via Real-Debrid and aria2"
  homepage "https://github.com/mhrsntrk/venaqui"
  version "1.1.5"
  license "MIT"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_darwin_amd64.tar.gz"
      sha256 "e1327d64e138f364a5c56065e3dec9115d82f96b945bacbf5e15f8f6552d0234"

      def install
        bin.install "venaqui"
      end
    end
    on_arm do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_darwin_arm64.tar.gz"
      sha256 "d9bc8bfe6449e4ddbaa0e58e61826fff5a5301045dd2d1b7ad9a545fc1758369"

      def install
        bin.install "venaqui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_linux_amd64.tar.gz"
        sha256 "50925673c5e22dd3e8fe3c522422e4ba5ad93a6639a147cdacda7751dc4c5321"

        def install
          bin.install "venaqui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_linux_arm64.tar.gz"
        sha256 "118481e23f6ede4a04bc4cf4c4c2f8f1db7c6099d25e8b57cfe0349fdbfb4680"

        def install
          bin.install "venaqui"
        end
      end
    end
  end

  test do
    system "#{bin}/venaqui", "version"
  end
end
