# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venaqui < Formula
  desc "CLI tool with TUI for downloading files via Real-Debrid and aria2"
  homepage "https://github.com/mhrsntrk/venaqui"
  version "1.1.5"
  license "MIT"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_darwin_amd64.tar.gz"
      sha256 "ebd281cadda2e2b8be21d287498bdc70ad64fd770a533de750c00a7d058e3eff"

      def install
        bin.install "venaqui"
      end
    end
    on_arm do
      url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_darwin_arm64.tar.gz"
      sha256 "37d4b94ab8f9355a22b55890c1551e617e1dd1780adc2b439114e224eae26c42"

      def install
        bin.install "venaqui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_linux_amd64.tar.gz"
        sha256 "05d59cfec06ee2d298298c3f17e13be15ad28918e77fabbe5e443538993f3bed"

        def install
          bin.install "venaqui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mhrsntrk/venaqui/releases/download/v1.1.5/venaqui_1.1.5_linux_arm64.tar.gz"
        sha256 "4f21a1be393999a3e8f9f6ac0c2687bd6391a7063287f4bb98843eed9725111f"

        def install
          bin.install "venaqui"
        end
      end
    end
  end

  test do
    system "#{bin}/venaqui", "version"
  end
end
